### ISSUE TITLE
Sends full-size images as thumbnails

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-s3#14]
Excerpt of a GraphQL response in admin/assets

![silverstripe - files 2017-10-10 14-12-45](https://user-images.githubusercontent.com/111025/31385916-44e645ba-adc5-11e7-91df-68cfb10fe7ab.png)

**Comment by obj63mc** [comment]
Hi @chillu - not sure if this is still an issue.  Testing on our production site and this module with #20 merged I am getting back the following - 

![Screen Shot 2019-04-08 at 8 57 43 AM](https://user-images.githubusercontent.com/443120/55729864-904aa900-59dc-11e9-8962-b5018af10bb4.png)

Looks like it is returning back specific 'Fit width' image files.  If you still see this issue let me know and I can look into it some more.

**Comment by madmatt** [comment]
@chillu I suspect this might be resolved in 0.3.0 or 0.4.0, if you get a chance to re-test could you let us know?

If not, I think we can consider this fixed with @obj63mc's recent changes.
