### ISSUE TITLE
RFC Move the caching to a separate module or to `silverstripe/assets`

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-s3#16]
Most of the plugin has nothing to do with S3 and just provides caching for low latency filesystem. It's coded in a generic way. You could literally give you site a different adapter and it would just work.

I think it should be in a separate non-S3 specific module or in the core assets module.

The following files would need to be moved.
* `Adapter`
  * `CacheAdapter`
  * `ProtectedCacheAdapter`
  * `PublicCacheAdapter`
* `Cache`
  * `ContentCache`
  * `ContentWarmer`
* `S3AssetStore`

This would only leave to S3 specific files: `ProtectedS3Adapter` and `PublicS3Adapter`.

**Comment by obj63mc** [comment]
With this module now using flysystem's cache adapter, not sure if this is needed any more.  Referencing #19 and #20

**Comment by madmatt** [comment]
@maxime-rainville Do you think this is still relevant? It's a bit more specific to S3 now, and relies on flysystem caching for metadata cache now, so is a little less generic.

We already have the assets module and flysystem itself as generic modules, I'm not sure we need another one? We can just create modules for another other filesystem we want to use (e.g. Rackspace, Azure Blob Storage or similar), hopefully leveraging on an existing Flysystem adapter for the hard work :-)

If you think this is still relevant feel free to re-open!

**Comment by maxime-rainville** [comment]
Sounds like your latest changes make this idea redundant. All good.
