### ISSUE TITLE
File metadata cache is not updated on un/publishing

### ISSUE THREAD

**Issue by filiplikavcan** [silverstripe/silverstripe-s3#19]
After I upload an image it shows a thumbnail which has protected url. This is correct. When I publish the file, the actual file is moved (or rather the name on S3 is changed) but the public metadata cache is not updated. The result is that url is not updated to public and is still pointing to a non existing protected file. After I manually delete the metadata cache it correctly uses public url. The same problem exists the other way around when I unpublish the file and its url remains public.

I tested it on clean SS4 install.

**Comment by filiplikavcan** [comment]
It could be caused by this: https://github.com/thephpleague/flysystem-aws-s3-v3/pull/159

**Comment by obj63mc** [comment]
Just checking if there is any update on this.  Essentially you can't use this module in the CMS as any time you try to upload images/publish them they show broken thumbnails.

**Comment by obj63mc** [comment]
This should be resolved now with the merge of #20.  @filiplikavcan let us know if you see any issues.

**Comment by madmatt** [comment]
Closing this issue as we've released 0.4.0 for this - thanks for your efforts @filiplikavcan and @obj63mc, and sorry this took so long!

**Comment by thats4shaw** [comment]
@madmatt is there anyway we can give Packagist a kick so it picks up 0.4.0?

**Comment by madmatt** [comment]
Hey @thats4shaw, sorry I forgot to comment back on here. I kicked Packagist and it seems to have picked up 0.4.0 now: https://packagist.org/packages/silverstripe/s3
