### ISSUE TITLE
Release a stable v1.0

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-s3#24]
I think once we've had a few weeks of people using 0.4.0 and we haven't had any major issues, we can promote that up to 1.0.0.

@obj63mc, what do you think? You're largely already using it, could you upgrade your sites to use 0.4.0 without any forks and see if it works for you? Same goes for anyone else too - it'd be great to get multiple real-world tests of 0.4.0 before we make something stable, especially given 1.0.0 will be the first properly semantic version release and we can't as easily making breaking API changes after that.

**Comment by obj63mc** [comment]
Can do. Will pull that down in the morning to a few of our sites and let you know of any issues. Right now I believe everything is exactly the same as my fork so we should be good.

**Comment by madmatt** [comment]
Hey @obj63mc, how's it looking for you after a month? If all is well, shall I release a v1.0?

**Comment by obj63mc** [comment]
No issues for us. Using in production for 3 sites 2 newly launched this month and another launching next and all is working well. Feel free to make it 1.0

**Comment by madmatt** [comment]
Fantastic, thanks! So this will transition the module into being semantically versioned, so from now any changes we make need to not break backwards compatibility (unless they're made on a new version as v2 etc).

Will create the new tag now.

Thanks @obj63mc for your testing!

**Comment by madmatt** [comment]
Version 1.0.0 has been released 🎉
