### ISSUE TITLE
Support Cloudfront 

### ISSUE THREAD

**Issue by mngreece** [silverstripe/silverstripe-s3#25]
Support for having a CloudFront distribution that has a s3 bucket for assets behind the distribution and only requests for public assets and can only be accessed from CloudFront,  i.e. https://some-domain.com/assets/

At the moment public the URL returned is always https://<AWS_BUCKET_NAME>.s3.<AWS_REGION>..amazonaws.com/xxxxx

**Comment by obj63mc** [comment]
You should be able to do this by specifying an options variable in your yaml config for the public adapter defining  the base_url 
https://flysystem.thephpleague.com/docs/adapter/aws-s3/

Would be something like 

    SilverStripe\S3\Adapter\PublicAdapter:
    constructor:
      s3Client: '%$Aws\S3\S3Client'
      bucket: '`AWS_BUCKET_NAME`'
      prefix: '`AWS_PUBLIC_BUCKET_PREFIX`'
      options:
         - base_url: 'https://....'

**Comment by mngreece** [comment]
I've extended the PublicAdapter but will try out the config option above - thanks.

**Comment by zanderwar** [comment]
@obj63mc 

Could you double check that? I've tried many variations but the base_url is never used despite evidently being passed through to the options parameter

**Comment by JoshuaCarter** [comment]
For anyone who stumbled on this, I found this worked:
```
SilverStripe\Core\Injector\Injector:
  Aws\S3\S3Client:
    constructor:
      configuration:
        endpoint: https://s3.{region}.{host}.com
```
Where host is amazonaws, or wasabisys, etc.
