### ISSUE TITLE
AWS Env Settings Mismatch

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-s3#27]
At the moment, the silverstripe/dynamodb and silverstripe/s3 modules use two different settings for the same AWS config:

```
AWS_REGION_NAME
AWS_ACCESS_KEY
AWS_SECRET_KEY
```

and

```
AWS_REGION
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
```

....respectively.

It would be good to standardise on one set or the other.

**Comment by obj63mc** [comment]
If you are using this module outside of AWS you have to add your own yaml config specifying the s3 client to use your key and secret. Those environment variables could be called anything really so there is nothing stopping someone from naming them the same. Feel free to provide a pull request for the readme and we can merge it. No code changes are needed.

**Comment by obj63mc** [comment]
Looking at Amazon's docs the names we are using are the default for the php sdk https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_environment.html

The documentation and setup of dynamodb module looks quite old too as the readme still mentions the ss environment php file which isn't used in 4.x any more.
