### ISSUE TITLE
Configuration ?

### ISSUE THREAD

**Issue by Fr3dj** [silverstripe/silverstripe-s3#28]
Hi There,
I am having a bit of trouble to configure the variables, the ReadMe is a bit light and I also cannot find any information about the SilverStripeS3AdapterTrait trait. 
Where Am I supposed to setup AWS_REGION, AWS_BUCKET_NAME, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY? Is this going into the _config file, a yml? 
Thank you.

**Comment by obj63mc** [comment]
You will want to setup those variables in your .env file locally. Then you can set your s3 client to connect using those by specifying it in your yaml config. Checkout https://github.com/silverstripe/silverstripe-s3/issues/26#issuecomment-505525388 for an example.
