### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by leochenftw** [silverstripe/silverstripe-s3#37]
Hi, can we please have the content in this page https://github.com/silverstripe/silverstripe-s3/issues/26#issuecomment-505525388 included in the README.md file? Maybe many don't need it, but it will help people who are new.

**Comment by obj63mc** [comment]
We can, it is basically mentioned in the Environment setup - "If running outside of an EC2 instance it will be necessary to specify an API key and secret." we just don't specifically provide the YML for you as you can technically add this where ever in your config or even set it up via PHP.

**Comment by leochenftw** [comment]
> We can, it is basically mentioned in the Environment setup - "If running outside of an EC2 instance it will be necessary to specify an API key and secret." we just don't specifically provide the YML for you as you can technically add this where ever in your config or even set it up via PHP.

Thank you for responding 👍
