### ISSUE TITLE
Uploading directly causes strange problems in assets

### ISSUE THREAD

**Issue by zanderwar** [silverstripe/silverstripe-s3#39]
Saving a file to the database/flysystem:

```
$contents = file_get_contents('some-image');
/** @var Image $img */
$img = Image::create();
$img->setFromString($contents, "some-image.jpg");
$img->Title = $product->Title;
$img->ParentID = $folder->ID;
$img->write();

// This is needed to build the thumbnails in asset manager
AssetAdmin::create()->generateThumbnails($img);
```

Everything works fine, the thumbnails and everything appear when you open up the AssetAdmin module and everything is loading from s3 nicely.

If you _then_ publish the image from it's unpublished state (via `$img->publishRecurisve()`), the images no longer display in asset admin and all URL's point to a signed URL with this response:

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
[REDACTED]
</Error>
```

-------

#### but...
If you upload the image directly to AssetAdmn, then the opposite of the above happens, the images can't be seen while unpublished, but can be seen when they are.

The only place the appears to be working correctly is when using `UploadField` and publishing on save (`$owns`)

Any idea?

Thanks

**Comment by zanderwar** [comment]
The solution mentioned in #33 only fixes the problem when uploading directly to asset admin

**Comment by zanderwar** [comment]
`FlysystemAssetStore::exists()` returns false and from there that triggers images to not display in the Asset Admin

**Comment by obj63mc** [comment]
So in the past, I have used the following to manually upload a file and publish it with SS4 and s3

```php
            $ssImage = Image::create();
            $ssImage->setFromLocalFile(sys_get_temp_dir().'/photo-'.$filename.'.jpg', 'Uploads/Cards/photo-'.$filename.'.jpg');
            $ssImage->publishFile();
            $ImageId = $ssImage->write();
            $sw->PhotoID = $ImageId;
            $id = $sw->write();
```

So from the example above we load the file, publish it to the public folder then write the record to the database. Looks like you should use the 'publishFile' function to actually publish it to your S3 bucket from the protected bucket. Also if you are looking for coding support it is better to post at forum.silverstripe.org or hit up their slack channel. 

As to the preview in the CMS being broken in Assets Admin that is known in the bug you mentioned above and should be fixed when assets admin pushes their fix for this. The work around I have provided will fix that for you for now.

**Comment by zanderwar** [comment]
Thanks, that appears to work.

FYI I did try everything that **used to work** .

https://stackoverflow.com/a/48683182/2266583

**Comment by zanderwar** [comment]
@obj63mc thanks for trying to help...

Sadly, this isstill an issue without further workarounds. I've put 16 years experience into 12 hours of debugging and I'm ashamed to say that this is probably the most tiring thing i've dealt with.

Run your code above twice on the same file, v2 is added to the database as expected but v1 loses its link to the S3 object and then begins to throw a server error when publishing

![image](https://user-images.githubusercontent.com/13566916/84501346-b3b46680-acf9-11ea-872e-f8fe8348616b.png)

then v3 gets worse

![image](https://user-images.githubusercontent.com/13566916/84501424-d9da0680-acf9-11ea-8937-99ba559ba897.png)

```
ERROR [Emergency]: Uncaught InvalidArgumentException: League\Flysystem\Filesystem::putStream expects argument #2 to be a valid resource.
IN POST /admin/assets/fileEditForm/4/
Line 111 in C:\wamp\www\blanksswiths3\vendor\league\flysystem\src\Filesystem.php

Source
======
  102:         return (bool) $this->getAdapter()->write($path, $contents, $config);
  103:     }
  104: 
  105:     /**
  106:      * @inheritdoc
  107:      */
  108:     public function putStream($path, $resource, array $config = [])
  109:     {
  110:         if ( ! is_resource($resource)) {
* 111:             throw new InvalidArgumentException(__METHOD__ . ' expects argument #2 to be a valid
       resource.');
  112:         }
  113: 
  114:         $path = Util::normalizePath($path);
  115:         $config = $this->prepareConfig($config);
  116:         Util::rewindStream($resource);
  117: 

Trace
=====
League\Flysystem\Filesystem->putStream(Products/MaxiCosi/mico-ap-baby-capsule.png, )
FlysystemAssetStore.php:954

SilverStripe\Assets\Flysystem\FlysystemAssetStore->moveBetweenFileStore(SilverStripe\Assets\FilenameParsing\ParsedFileID, League\Flysystem\Filesystem, SilverStripe\Assets\FilenameParsing\FileIDHelperResolutionStrategy, League\Flysystem\Filesystem, SilverStripe\Assets\FilenameParsing\FileIDHelperResolutionStrategy)
FlysystemAssetStore.php:800

SilverStripe\Assets\Flysystem\FlysystemAssetStore->publish(Products/MaxiCosi/mico-ap-baby-capsule.png, f5aeeb6c0251b295c39bf720bdf0b78efce47005)
AssetControlExtension.php:311

SilverStripe\Assets\AssetControlExtension->publishAll(Array)
AssetControlExtension.php:144

SilverStripe\Assets\AssetControlExtension->processManipulation(SilverStripe\Assets\AssetManipulationList)
AssetControlExtension.php:93
```

**Comment by zanderwar** [comment]
My real problem was left over deleted-file-artifacts that were preventing the same file from being recreated in S3. This was due to me frequently emptying the bucket while testing (the file names would become reserved for a period of time and preventing anything from taking it's name). 

I'd wonder if there's an exception caught somewhere in AWS SDK that's trying to tell us this.

**Comment by obj63mc** [comment]
I couldn't say if the aws sdk would be throwing an error or not as odds are the flysystem adapter would handle that not necessarily the Silverstripe code.  

Overall though I would definitely make sure you are working with a clean bucket and using Silverstripe only to edit/upload files there.  For example if you manually upload a file to S3, Silverstripe will have no idea it is there and it won't show in the assets section.  

One thing you might want to do is start with a clean directory path so in your config, you can add a prefix to your public path, then test some programatic uploads there and once you have everything worked out you can then switch to a different public path prefix for your staging/production environments.  For example we use this pattern a lot on our sites env files.

```env
AWS_PROTECTED_BUCKET_PREFIX=protected/{sitename}/dev
AWS_PUBLIC_BUCKET_PREFIX=public/{sitename}/dev
```

Then when we need to test something weird we might do -

```env
AWS_PROTECTED_BUCKET_PREFIX=protected/{sitename}/dev-{featurename}
AWS_PUBLIC_BUCKET_PREFIX=public/{sitename}/dev-{featurename}
```

Lastly it might be good to make sure any weird orphan data is cleared out in your database, either start fresh or while testing programatic uploads make sure the files have a unique filename and that way you can ensure there are no caching issues or anything weird like that.

**Comment by zanderwar** [comment]
Thanks for that, some really good ideas. Appreciate you writing that up to me.

Sadly this still has some problems. Happy to give you access to the repo so you can see for yourself, you'd only find an empty SS install with S3 hooked up to it. I was sorting out logistics before I started to build any of the project, so `create-project`, `require silverstripe/s3` and configure `.env` is all I've done, spent the rest of my time trying to work out why it's behaving weird.

I've ended up just hashing the file names so they don't cause any of that strange behavior.
