### ISSUE TITLE
Silverstripe 4.5.x

### ISSUE THREAD

**Issue by apuckey** [silverstripe/silverstripe-s3#41]
Tested on 4.3.6 and works without any dramas.
Tested on 4.4.6 and mostly works except for previews.
Tested on 4.5 using exactly the same config but it refuses to work at all, is the config different for 4.5 ?

base install of both versions purely with the silverstripe/s3 module, env variables and yml file to provide credentials.

**Comment by polycode-nz** [comment]
To add, I get this error message 

> Uncaught SilverStripe\Core\Injector\InjectorNotFoundException: ReflectionException: Class League\Flysystem\Filesystem.public does not exist in /var/www/html/vendor/silverstripe/framework/src/Core/Injector/InjectionCreator.php:17

**Comment by obj63mc** [comment]
Should work just fine. I have used this on all current versions including 4.6.0 which was just released. 

I would make sure your environment variables are set properly and that you have run a dev build and flush to make sure the module is active. Also confirm that the module is actually installed via composer. Other than that we would need more error information / your exact configuration to troubleshoot. Feel free to post on the SS forums for more troubleshooting help.
