### ISSUE TITLE
Connection refused for URI

### ISSUE THREAD

**Issue by paulblaze** [silverstripe/silverstripe-s3#49]
When we try to upload image we got below error and exception. Kindly advise us regarding this

1. Uncaught InvalidArgumentException: League\Flysystem\Filesystem::putStream expects argument #2 to be a valid resource in /vendor/league/flysystem/src/Filesystem.php:111

2. Error executing "GetObject" on "https://XXXX.ap-south-1.linodeobjects/protected/Uploads/475a86907f/Round130.png"; AWS HTTP error: Connection refused for URI https://XXXX.ap-south-1.linodeobjects.com/protected/Uploads/475a86907f/Round130.png

**Comment by obj63mc** [comment]
If you are getting a connection refused error on your 'protected' assets - which are not open to the public, then you are either missing a specific config variable such as your AWS Secret and Key or something is not configured on your bucket properly.  

The AWSS3 adapter is from the league/flysystem package not from us.  

Please check to ensure your configuration is setup properly based off of our readme.

If you need support on setting up your environment I would recommend hitting the forums - https://forum.silverstripe.org/
