### ISSUE TITLE
SS Assets 2.0+ upgraded flysystem to v3 - compatibility issues with this module

### ISSUE THREAD

**Issue by obj63mc** [silverstripe/silverstripe-s3#62]
Currently when trying to upgrade to recipe CMS 5.1 which specifically installs https://github.com/silverstripe/silverstripe-assets/releases/tag/2.1.0 puts flysystem to v3. Before SS Assets 2.0 alpha was being installed which was still on flysystem v1.

This means this module will not work with this new version and that all the caching functionality will have to be removed or a full custom cache solution/ different module built out as the cached adapters that are currently used not available for v3.

**Comment by GuySartorelli** [comment]
Just to be clear, assets 2.0.0 is when the flysystem dependency was upgraded
https://github.com/silverstripe/silverstripe-assets/blob/2.0.0/composer.json

**Comment by obj63mc** [comment]
Correct noted as much in the PR after some more researching and resolving the updates.

silverstripe/assets v2.0 beta switched to flysystem v3. Users running SS5 and this module were getting silverstripe/assets 2.0 alpha installed which was not ideal.

PR should be good to resolve this.

**Comment by obj63mc** [comment]
Updated title and initial description of the issue
