### ISSUE TITLE
Asset Management Timing Out on Heroku / Bucketeer (S3) Resource Integration

### ISSUE THREAD

**Issue by zaidaldabbagh** [silverstripe/silverstripe-s3#68]
Hi all, my SS5 Asset management is timing out on Heroku / Bucketeer (S3) Resource Integration.

I'm currently on this SilverStripe 5 version:

```
"name": "silverstripe/recipe-cms",
"version": "5.1.0"
```

And on this SilverStripe S3 version:

```
"name": "silverstripe/s3",
"version": "3.0.0"
```

Any idea what is causing this outage?

**Comment by zaidaldabbagh** [comment]
Thnx @obj63mc that might be it :) ... I have two options I guess, either break down my logos into subfolders so it doesn't time out, i.e. work with Heroku's constraints, or try and raise a ticket with the Bucketeer team to see if we can extend that timeout, however the latter won't happen, as they probably have the timeout in place across all of their instances.

**Comment by wilr** [comment]
@zaidaldabbagh I've written a PR which improves caching and reduces the number of S3 calls now (https://github.com/silverstripe/silverstripe-s3/pull/70) that should hopefully speed things up for you.
