### ISSUE TITLE
Assets loading gets up to 40 or more seconds

### ISSUE THREAD

**Issue by jcbbt** [silverstripe/silverstripe-s3#69]
We've used the package as instructed here on the manual. We've entered the necessary details & followed the necessary steps to get the package working. 

As the assets of the project gets large & more folders get added, it seems that loading the assets uploader (choosing existing assets to use or to just browse the files uploaded) gets slower overtime. We have already incorporated caching but even with caching it still takes more than 10 seconds to load which is very annoying when uploading multiple files or setting up blocks continuously.

We have checked related issues and it seems that this issue somehow relates to my problem: https://github.com/silverstripe/silverstripe-s3/issues/48

Do you know how to solve this or any pointers, suggestions or directions you can share to make the loading faster?

**Comment by wilr** [comment]
Closing as duplicate - see https://github.com/silverstripe/silverstripe-s3/issues/48 for discussion
